# This is a basic workflow to help you get started with Actions

name: React build test

on:
  push:
    branches: ["main", "events1"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.X]
    steps:
      - uses: actions/checkout@v3
      - name: Using Node js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
